2019-11-28T18:35:03.7732751+02:00;VSTestExecutionThread;Info;SpecFlow+Runner execution started
2019-11-28T18:35:03.7742713+02:00;VSTestExecutionThread;Info;SpecFlow+Runner 3.1.36 in Framework clr40 in x86 mode execution started
2019-11-28T18:35:03.7742713+02:00;VSTestExecutionThread;Info;TestAdapter Location: C:\Users\raminta.linkute\Desktop\Seb\OpenWeatherTests\OpenWeatherAPITests\bin\Debug\TechTalk.SpecRun.VisualStudio.TestAdapter.dll
2019-11-28T18:35:03.8261328+02:00;VSTestExecutionThread;Info;SpecRun: running tests in C:\Users\raminta.linkute\Desktop\Seb\OpenWeatherTests\OpenWeatherAPITests\bin\Debug\OpenWeatherAPITests.dll
2019-11-28T18:35:03.8261328+02:00;VSTestExecutionThread;Info;Output folder configured to "C:\Users\raminta.linkute\Desktop\Seb\OpenWeatherTests\TestResults" (default)
2019-11-28T18:35:03.8261328+02:00;VSTestExecutionThread;Info;Profile: 
2019-11-28T18:35:03.8500692+02:00;VSTestExecutionThread;Info;Log file path: C:\Users\raminta.linkute\Desktop\Seb\OpenWeatherTests\TestResults\Unnamed project__2019-11-28T183503.log
2019-11-28T18:35:03.8620370+02:00;VSTestExecutionThread;Info;SpecFlow+Runner Evaluation Mode: Please purchase at http://www.specflow.org/plus to remove test execution delay.
2019-11-28T18:35:03.8690190+02:00;Thread#13;Info;Checking license
2019-11-28T18:35:03.8829816+02:00;Thread#13;Info;Evaluation mode: test execution starts in 8 seconds... (this delay is removed in the registered version)
2019-11-28T18:35:11.8848177+02:00;Thread#13;Info;Evaluation delay finished.
2019-11-28T18:35:11.8888068+02:00;Thread#13;Info;License check completed
2019-11-28T18:35:11.8888068+02:00;Thread#13;Info;starting test run
2019-11-28T18:35:11.8948243+02:00;Thread#13;Info;Discovering target: Default
2019-11-28T18:35:11.8948243+02:00;Thread#13;Info;Discovering tests from assembly: C:\Users\raminta.linkute\Desktop\Seb\OpenWeatherTests\OpenWeatherAPITests\bin\Debug\OpenWeatherAPITests.dll
2019-11-28T18:35:12.1630742+02:00;Thread#13;Info;Discovered tests from assembly: C:\Users\raminta.linkute\Desktop\Seb\OpenWeatherTests\OpenWeatherAPITests\bin\Debug\OpenWeatherAPITests.dll
2019-11-28T18:35:12.1640712+02:00:Test Suite Dump
2019-11-28T18:35:12.1650686+02:00:#0: Unnamed project/ - 
2019-11-28T18:35:12.1650686+02:00:#1: Default - 
2019-11-28T18:35:12.1650686+02:00:#2: OpenWeatherAPITests - 
2019-11-28T18:35:12.1650686+02:00:#9: CallCurrentWeatherDataForSeveralCities - 
2019-11-28T18:35:12.2010052+02:00:#10: Call for several city IDs - TestAssembly:OpenWeatherAPITests/Feature:CallCurrentWeatherDataForSeveralCities/Scenario:Call+for+several+city+IDs
2019-11-28T18:35:12.2010052+02:00:End: Test Suite Dump
2019-11-28T18:35:12.2209546+02:00:Thread#0:Scheduler: get next test for thread 0
2019-11-28T18:35:12.2219502+02:00:Thread#:Scheduler: testitem #10 from normal test queue 
2019-11-28T18:35:12.2219502+02:00:Thread#0:Scheduler: considering testitem #10 for thread 0
2019-11-28T18:35:12.2269028+02:00:Thread#0:TestItem#10:testItemMatchesCurrentTestThread:UnSpecific
2019-11-28T18:35:12.2269028+02:00:Thread#0:TestItem#10:runsOnOneOtherThreadSpecific:False
2019-11-28T18:35:12.2269028+02:00:Thread#0:TestItem#10:runsOnOneOtherThreadUnspecific:False
2019-11-28T18:35:12.2269028+02:00:Thread#0:Scheduler: using testitem #10 for thread 0
2019-11-28T18:35:12.2279002+02:00:Thread#0:Scheduler: Test #10 is scheduled for thread
2019-11-28T18:35:12.2288972+02:00:Thread#0:Scheduler: with testItemExecutionIndex 0
2019-11-28T18:35:12.2318897+02:00:Thread #0: creating new test thread executor for OpenWeatherAPITests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (target: Default)
2019-11-28T18:35:12.2338848+02:00:Thread #0: Creating test assembly executor for execution model AppDomain
2019-11-28T18:35:12.2358792+02:00:Thread #0: Creating test assembly executor for execution model AppDomain
2019-11-28T18:35:12.2369116+02:00:Thread #0: using TechTalk.SpecRun.Framework.Execution.InProcess.InProcAppDomainTestAssemblyExecutorHost to execute tests
2019-11-28T18:35:12.4885376+02:00:Thread#0:T:-> Loading plugin C:\Users\raminta.linkute\Desktop\Seb\OpenWeatherTests\OpenWeatherAPITests\bin\Debug\SpecRun.Runtime.SpecFlowPlugin.dll
2019-11-28T18:35:12.4945138+02:00:Thread#0:T:-> Using default config
2019-11-28T18:35:12.9466140+02:00:Thread#0: Test #10/0 is started on thread #0
2019-11-28T18:35:12.9655638+02:00:Thread#0:B:Given IDs '524901,703448,2643743' exists in the system
2019-11-28T18:35:13.0892318+02:00:Thread#0:T:done: CallCurrentWeatherDataForSeveralCitiesSteps.GivenIDsExistsInTheSystem("524901,703448,264...") (0.0s)
2019-11-28T18:35:13.0892318+02:00:Thread#0:B:When I request to get the weather data by ids
2019-11-28T18:35:13.3145576+02:00:Thread#0:T:done: CallCurrentWeatherDataForSeveralCitiesSteps.WhenIRequestToGetTheWeatherDataByIds() (0.2s)
2019-11-28T18:35:13.3145576+02:00:Thread#0:B:Then Count '3' is returned in the response
2019-11-28T18:35:13.3584401+02:00:Thread#0:T:error: Object reference not set to an instance of an object.
2019-11-28T18:35:13.3634269+02:00:Thread#0:B:And status code 'OK' is returned in the response
2019-11-28T18:35:13.3644243+02:00:Thread#0:T:skipped because of previous errors
2019-11-28T18:35:13.4242969+02:00:Thread#0:TestItem#10:Scheduler: reschedule tests for testitem #10
2019-11-28T18:35:13.4252615+02:00:Thread#0:Scheduler: get next test for thread 0
2019-11-28T18:35:13.4252615+02:00:Thread#:Scheduler: dequeuing a rescheduled testitem: #10
2019-11-28T18:35:13.4252615+02:00:Thread#0:Scheduler: considering testitem #10 for thread 0
2019-11-28T18:35:13.4252615+02:00:Thread#0:TestItem#10:testItemMatchesCurrentTestThread:UnSpecific
2019-11-28T18:35:13.4252615+02:00:Thread#0:TestItem#10:runsOnOneOtherThreadSpecific:False
2019-11-28T18:35:13.4252615+02:00:Thread#0:TestItem#10:runsOnOneOtherThreadUnspecific:False
2019-11-28T18:35:13.4252615+02:00:Thread#0:Scheduler: using testitem #10 for thread 0
2019-11-28T18:35:13.4252615+02:00:Thread#0:Scheduler: Test #10 is scheduled for thread
2019-11-28T18:35:13.4252615+02:00:Thread#0:Scheduler: with testItemExecutionIndex 1
2019-11-28T18:35:13.4352353+02:00:Thread#0: Test #10/0 is finished on thread #0 as Failed within 0.4876243 seconds
2019-11-28T18:35:13.4372428+02:00:Thread#0: Test #10/1 is started on thread #0
2019-11-28T18:35:13.4372428+02:00:Thread#0:B:Given IDs '524901,703448,2643743' exists in the system
2019-11-28T18:35:13.4372428+02:00:Thread#0:T:done: CallCurrentWeatherDataForSeveralCitiesSteps.GivenIDsExistsInTheSystem("524901,703448,264...") (0.0s)
2019-11-28T18:35:13.4372428+02:00:Thread#0:B:When I request to get the weather data by ids
2019-11-28T18:35:13.4952574+02:00:Thread#0:T:done: CallCurrentWeatherDataForSeveralCitiesSteps.WhenIRequestToGetTheWeatherDataByIds() (0.1s)
2019-11-28T18:35:13.4952574+02:00:Thread#0:B:Then Count '3' is returned in the response
2019-11-28T18:35:13.4962544+02:00:Thread#0:T:error: Object reference not set to an instance of an object.
2019-11-28T18:35:13.4962544+02:00:Thread#0:B:And status code 'OK' is returned in the response
2019-11-28T18:35:13.4962544+02:00:Thread#0:T:skipped because of previous errors
2019-11-28T18:35:13.4962544+02:00:Thread#0:Scheduler: get next test for thread 0
2019-11-28T18:35:13.4972521+02:00:Thread#:Scheduler: dequeuing a rescheduled testitem: #10
2019-11-28T18:35:13.4972521+02:00:Thread#0:Scheduler: considering testitem #10 for thread 0
2019-11-28T18:35:13.4972521+02:00:Thread#0:TestItem#10:testItemMatchesCurrentTestThread:UnSpecific
2019-11-28T18:35:13.4972521+02:00:Thread#0:TestItem#10:runsOnOneOtherThreadSpecific:False
2019-11-28T18:35:13.4972521+02:00:Thread#0:TestItem#10:runsOnOneOtherThreadUnspecific:False
2019-11-28T18:35:13.4972521+02:00:Thread#0:Scheduler: using testitem #10 for thread 0
2019-11-28T18:35:13.4972521+02:00:Thread#0:Scheduler: Test #10 is scheduled for thread
2019-11-28T18:35:13.4972521+02:00:Thread#0:Scheduler: with testItemExecutionIndex 2
2019-11-28T18:35:13.4972521+02:00:Thread#0: Test #10/1 is finished on thread #0 as Failed within 0.0600093 seconds
2019-11-28T18:35:13.4972521+02:00:Thread#0: Test #10/2 is started on thread #0
2019-11-28T18:35:13.4972521+02:00:Thread#0:B:Given IDs '524901,703448,2643743' exists in the system
2019-11-28T18:35:13.4982495+02:00:Thread#0:T:done: CallCurrentWeatherDataForSeveralCitiesSteps.GivenIDsExistsInTheSystem("524901,703448,264...") (0.0s)
2019-11-28T18:35:13.4982495+02:00:Thread#0:B:When I request to get the weather data by ids
2019-11-28T18:35:13.5527961+02:00:Thread#0:T:done: CallCurrentWeatherDataForSeveralCitiesSteps.WhenIRequestToGetTheWeatherDataByIds() (0.1s)
2019-11-28T18:35:13.5527961+02:00:Thread#0:B:Then Count '3' is returned in the response
2019-11-28T18:35:13.5537946+02:00:Thread#0:T:error: Object reference not set to an instance of an object.
2019-11-28T18:35:13.5537946+02:00:Thread#0:B:And status code 'OK' is returned in the response
2019-11-28T18:35:13.5537946+02:00:Thread#0:T:skipped because of previous errors
2019-11-28T18:35:13.5537946+02:00:Thread#0:Scheduler: get next test for thread 0
2019-11-28T18:35:13.5537946+02:00:Thread#:Scheduler: at the end of normal test queue
2019-11-28T18:35:13.5537946+02:00:Thread#0:Scheduler: enumerator for thread is at end
2019-11-28T18:35:13.5537946+02:00:Thread#0:Scheduler: No more tests for thread
2019-11-28T18:35:13.5637673+02:00:Thread#0: Test #10/2 is finished on thread #0 as Failed within 0.0665152 seconds
2019-11-28T18:35:13.6066520+02:00:Trying to cancel thread
2019-11-28T18:35:13.6066520+02:00:Thread cancelled
2019-11-28T18:35:13.6116389+02:00:Thread#-1:Scheduler: get next test for thread -1
2019-11-28T18:35:13.6126359+02:00:Thread#:Scheduler: at the end of normal test queue
2019-11-28T18:35:13.6126359+02:00:Thread#-1:Scheduler: enumerator for thread is at end
2019-11-28T18:35:13.6166258+02:00;Thread#13;Info;test run finished
2019-11-28T18:35:13.6166258+02:00;Thread#13;Info;publishing test results
2019-11-28T18:35:13.6365722+02:00;Thread#13;Info;test results published
2019-11-28T18:35:13.6365722+02:00;Thread#13;Info;generating reports
2019-11-28T18:35:13.7353087+02:00;Thread#13;Info;Starting external report generation process
2019-11-28T18:35:14.2419532+02:00;Thread#13;Error;Could not generate test run result reports. An error occurred in the generator.
2019-11-28T18:35:14.2419532+02:00;Thread#13;Error;External program returned exit code '-1'
2019-11-28T18:35:14.2429506+02:00;Thread#13;Info;Failed generating reports
2019-11-28T18:35:14.2519259+02:00:Total: 1 (test executions: 3)
2019-11-28T18:35:14.2539217+02:00:Succeeded: 0
2019-11-28T18:35:14.2539217+02:00:Ignored: 0
2019-11-28T18:35:14.2549260+02:00:Pending: 0
2019-11-28T18:35:14.2549260+02:00:Skipped: 0
2019-11-28T18:35:14.2549260+02:00:Failed: 1
2019-11-28T18:35:14.2648918+02:00;VSTestExecutionThread;Info;Adding attachments to VSTest
========== End of log file ==========
